# Generated by Django 6.0.1 on 2026-01-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hostelreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
